.pragma library

var COLOR_FOREGROUND            = '#191919'
var COLOR_INVERTED_FOREGROUND   = '#ffffff'
var COLOR_SECONDARY_FOREGROUND  = '#8c8c8c'

var DEFAULT_MARGIN  = 16
var PADDING_LARGE   = 8
var PADDING_XSMALL  = 2

var FONT_FAMILY         = 'Nokia Pure Text'
var FONT_FAMILY_BOLD    = 'Nokia Pure Text Bold'
var FONT_FAMILY_LIGHT   = 'Nokia Pure Text Light'

var FONT_LSMALL     = 22
var FONT_DEFAULT    = 24
var FONT_SLARGE     = 26
var FONT_XLARGE     = 32

var HEADER_DEFAULT_TOP_SPACING_LANDSCAPE    = 16
var HEADER_DEFAULT_TOP_SPACING_PORTRAIT     = 20
var HEADER_DEFAULT_HEIGHT_PORTRAIT          = 72
var HEADER_DEFAULT_HEIGHT_LANDSCAPE         = 52

var LIST_ITEM_HEIGHT_DEFAULT = 80
